// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganicSoft.Infraestructura;

namespace OrganicSoft.Infraestructura.Migrations
{
    [DbContext(typeof(OrganicSoftContext))]
    [Migration("20211022185810_MyMigration")]
    partial class MyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrganicSoft.Dominio.Componente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoComboId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductoComboId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Componente");
                });

            modelBuilder.Entity("OrganicSoft.Dominio.Descuento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoDescuento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<double>("PorcentajeDescuento")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Descuento");
                });

            modelBuilder.Entity("OrganicSoft.Dominio.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadExistente")
                        .HasColumnType("int");

                    b.Property<int>("CantidadVendidad")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoProducto")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Decripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DescuentoID")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimoStock")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<double>("PrecioConDescuento")
                        .HasColumnType("float");

                    b.Property<string>("Presentacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DescuentoID");

                    b.ToTable("Producto");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Producto");
                });

            modelBuilder.Entity("OrganicSoft.Dominio.ProductoCombo", b =>
                {
                    b.HasBaseType("OrganicSoft.Dominio.Producto");

                    b.Property<double>("Utilidad")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("ProductoCombo");
                });

            modelBuilder.Entity("OrganicSoft.Dominio.ProductoSimple", b =>
                {
                    b.HasBaseType("OrganicSoft.Dominio.Producto");

                    b.HasDiscriminator().HasValue("ProductoSimple");
                });

            modelBuilder.Entity("OrganicSoft.Dominio.Componente", b =>
                {
                    b.HasOne("OrganicSoft.Dominio.ProductoCombo", null)
                        .WithMany("Componetes")
                        .HasForeignKey("ProductoComboId");

                    b.HasOne("OrganicSoft.Dominio.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("OrganicSoft.Dominio.Producto", b =>
                {
                    b.HasOne("OrganicSoft.Dominio.Descuento", "Descuento")
                        .WithMany()
                        .HasForeignKey("DescuentoID");

                    b.Navigation("Descuento");
                });

            modelBuilder.Entity("OrganicSoft.Dominio.ProductoCombo", b =>
                {
                    b.Navigation("Componetes");
                });
#pragma warning restore 612, 618
        }
    }
}
